myWarp_Database:
  user: xxx
  password: xxx
  dbName: xxx
  ip: localhost
  port: 3306
maps:
  The Red Book:
    world: hub
    world_coordinates:
      y: -32
      pos1:
        x: -4077
        z: -4338
      pos2:
        x: -4073
        z: -4335
    marker_radius: 0.1
    pages:
      The Shire:
        no: 1
        padding:
          left: 0.5
          top: 0
          right: 0.5
          bottom: 0
        map_coordinates:
          pos1:
            x: -5000
            z: -5000
          pos2:
            x: -3000
            z: -3500
        links:
          West of Middle-earth:
            x: -5000
            z: -3500
          Gondor:
            x: -3500
            z: -3500
        warps:
          Hobbiton: {}
          Tuckborrough: {}
          Brandy Hall: {}
          Waymoot: {}
          Frogmorton: {}
          Nobottle: {}
          Overhill: {}
          Willowbottom: {}
          Whitfurrows: {}
      Gondor:
        no: 3
        map_coordinates:
          pos1:
            x: 2000
            z: 500
          pos2:
            x: 12000
            z: 6500
        links:
          West of Middle-earth:
            x: 2000
            z: 6500
          The Shire:
            x: 3000
            z: 500
        warps:
          Edoras: {}
          Erech: {}
          Calembel: {}
          Linhir: {}
          Ethring: {}
          Pelargir: {}
          Cair Andros: {}
          Minas Morgul: {}
          Black Gate: {}
          Falls of Rauros: {}
          Minas Tirith:
            message:
            radius: 200
            priority: 10
      West of Middle-earth:
        no: 2
        map_coordinates:
          pos1:
            x: -12000
            z: -1200
          pos2:
            x: 17000
            z: 14500
        links:
          The Shire:
            x: -10000
            z: -1200
          Gondor:
            x: 15000
            z: 14500
        warps:
          Fornost: {}
          Rivendell: {}
          Hobbiton: {}
          Mithlond: {}
          Tharbad: {}
          Isengard: {}
          Helm's Deep: {}
          Dol Amroth: {}
          Lothlorien: {}
          Moria West Gate: {}
          Pelargir: {}
          Minas Tirith:
            message:
            radius: 200
            priority: 10
          Falls of Rauros:
            message:
          Black Gate: {}
  The Thain's Book:
    copy of: The Red Book
    world: world
    world_coordinates:
      y: -32
      pos1:
        x: -4087
        z: -4338
      pos2:
        x: -4083
        z: -4335


    