name: ${project.artifactId}
version: ${project.version}
main: com.mcmiddleearth.mapInteraction.MapsPlugin
api-version: '1.21'
depend: [ MCME-Base, ModelEngine ]
load: POSTWORLD
authors: [ Eriol_Eandur ]
description: Interactive Maps for MCME
